name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t workstationbynick/myapp:${{ github.sha }} .

    - name: Push Docker image
      run: docker push workstationbynick/myapp:${{ github.sha }}

  dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Docker container
      run: docker run --name myapp-container -d workstationbynick/myapp:${{ github.sha }}

    - name: Run tests
      run: docker exec myapp-container pytest dev/test_app.py || true

  deploy:
    runs-on: ubuntu-latest
    needs: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Staging
      run: |
        docker pull workstationbynick/myapp:${{ github.sha }}
        docker run -d -p 80:80 workstationbynick/myapp:${{ github.sha }}
